### ISSUE TITLE
Editing an existing journal entry in Redmine 3.3 no longer will focus textbox correctly

### ISSUE THREAD

**Issue by jdkemme** [tleish/redmine_editor_preview_tab#14]
JS code will no longer append the onSuccess script, as the edit link no longer has an onclick attribute, or an associated image tag (moved to css).

`var focus = function() {
    var $this = $(this);
    var $editLink = $this.find('a:has(img[alt=Edit])');`

editlink is undefined.

edit.js.erb may need to be extended instead to add the extra .focus() script now that it uses unobtrusive ajax async call.

**Comment by tleish** [comment]
Sounds like you might be familiar with the code.  It would be great it you could put together a pull request.

**Comment by tleish** [comment]
should be resolved
