### ISSUE TITLE
Error in js with Redmine 3.4.2

### ISSUE THREAD

**Issue by Mathieu4D** [tleish/redmine_editor_preview_tab#18]
Hello,
I just have setup a new Redmine server 3.4.2. 
I am not a js dev, just install the plugin.

This plugin works fine, but this error can be bother

sorry for my bad english
Can you help me to remove the error ?

thank you

![image](https://user-images.githubusercontent.com/3341083/31131914-c6f24c58-a85b-11e7-9e9d-7e3981d292b6.png)

**Comment by tleish** [comment]
should be resolved
