### ISSUE TITLE
Only works in Wiki

### ISSUE THREAD

**Issue by dreampet** [tleish/redmine_editor_preview_tab#4]
It only works in Wipi page editor, in the other editor(News, Documents, Description of Project setting,etc),click Preview tab always show empty content.

My system Info:
Environment:
  Redmine version                3.2.0.stable
  Ruby version                      2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                      4.2.5.1
  Environment                      production
  Database adapter              Mysql2
SCM:
  Mercurial                      2.8.2
  Cvs                              1.12.13
  Git                                1.9.1
  Filesystem  
Redmine plugins:
  a_common_libs                       2.0.0
  advanced_roadmap_v2          2.4.2
  clipboard_image_paste          1.10
  file_servers                             3.0.2
  redmine_banner                     0.1.1
  redmine_checklists                 3.1.3
  redmine_code_review            0.7.0
  redmine_editor_preview_tab  0.1.0
  redmine_issue_badge            0.0.2
  redmine_login_audit               0.2.3
  redmine_remote_revision_url    0.3.0
  redmine_revision_branches      0.3.0
  redmine_work_time                   0.3.1

**Comment by tleish** [comment]
It was previously tested in Issues and Wiki, but not in News or others.  It should behave better now.

Note that some areas do not have a preview provided by Redmine (like Projects description).  This plugin currently only supports areas in which the preview is already provided by Redmine.

In the areas where preview isn't supported, the Preview tab will not also display.
